image: node:latest

stages:
  - computation
  - build
  - jest

cache:
  paths:
    - node_modules/

install_and_build:
  stage: build
  script:
    - npm install
    - npm build
  artifacts:
    paths:
      - build/

test_application:
  stage: jest
  script:
    - CI=true
    - yarn test
  artifacts:
    paths:
      - ./