stages:
  - computation
  - build
  - jest

cache:
  paths:
    - node_modules/

install_and_build:
  stage: build
  image: node:latest
  before_script:
    - cd frontend
  script:
    - npm install
    - npm build
  after_script:
    - cd ..
  artifacts:
    paths:
      - build/

test_application:
  stage: jest
  image: node:latest
  script:
    - CI=true
    - yarn test
  artifacts:
    paths:
      - ./