image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_and_build:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

test_application:
  stage: test
  script:
    - CI=true
    - yarn test
  artifacts:
    paths:
      - ./