image: python:3.8

stages:
  - computation
#  - controller
#  - service

computation:
  stage: computation
  cache:
    policy: push
  before_script:
    - pip install pytest
  script:
    - python -m pytest backend/tests/TestComputation 


#controller:
#  stage: controller
#  cache:
#    policy: push
#  before_script:
#    - pip install pytest
#  script:
#    - python -m pytest tests/TestController 


#service:
#  stage: service
#  cache:
#    policy: push
#  before_script:
#    - pip install pytest
#  script:
#    - python -m pytest tests/TestService 